### ISSUE TITLE
Null value error on txt export

### ISSUE THREAD

**Issue by Selovert** [ReagentX/imessage-exporter#42]
_To preface: I'm not familiar with rust, but will try to provide helpful information!_

I'm running `imessage-exporter -f txt` and seeing the following output:
```
Building cache...
[1/4] Caching chats...
[2/4] Caching chatrooms...
[3/4] Caching participants...
[4/4] Caching reactions...
Cache built!
Exporting to /Users/tassilo/imessage_export as txt...
⠓ [2s] [################>---] 103216/123664 (39,193.6516/s, ETA: 1s)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/tassilo/.cargo/registry/src/github.com-1ecc6299db9ec823/imessage-exporter-0.1.2/src/exporters/txt.rs:337:42
```

Attempted to pull a backtrace by running `RUST_BACKTRACE=full imessage-exporter -f txt`:
```
stack backtrace:
   0:        0x1041ba34c - std::backtrace_rs::backtrace::libunwind::trace::hbe97f4303076f99a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1041ba34c - std::backtrace_rs::backtrace::trace_unsynchronized::hb462a91ac605b16b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1041ba34c - std::sys_common::backtrace::_print_fmt::h555c176cf2344151
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x1041ba34c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84d5e26d26c914d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1041d526c - core::fmt::write::h07c7e4739f78f3b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:        0x1041b6f5c - std::io::Write::write_fmt::h4a3c5f094ffc65e8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:        0x1041ba160 - std::sys_common::backtrace::_print::h03a1c9ac6001091a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x1041ba160 - std::sys_common::backtrace::print::h6fc2cc8be2392a8e
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x1041bb7b4 - std::panicking::default_hook::{{closure}}::h3bb44ba6ff437e23
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:        0x1041bb50c - std::panicking::default_hook::h92c6668a1a98ae8c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:        0x1041bbdf0 - std::panicking::rust_panic_with_hook::h9b8acc949e1fb807
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:        0x1041bbbc4 - std::panicking::begin_panic_handler::{{closure}}::hfc38b2cc56e3623c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:577:13
  12:        0x1041ba7b4 - std::sys_common::backtrace::__rust_end_short_backtrace::hbafd151207fc448f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x1041bb954 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:        0x1041e8b38 - core::panicking::panic_fmt::h8c7f3d540a75578f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:        0x1041e8bcc - core::panicking::panic::h2505ca165b8854d6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
  16:        0x1040f9764 - <imessage_exporter::exporters::txt::TXT as imessage_exporter::exporters::exporter::Writer>::format_message::h1bcefd6001801411
  17:        0x1040f69c0 - <imessage_exporter::exporters::txt::TXT as imessage_exporter::exporters::exporter::Exporter>::iter_messages::h5ed45f1370a5180d
  18:        0x1041017ec - imessage_exporter::app::runtime::Config::start::h1b7f6ac2978263f9
  19:        0x1040f2908 - imessage_exporter::main::h38ca28207216a674
  20:        0x1040fe79c - std::sys_common::backtrace::__rust_begin_short_backtrace::h85560146c1c1ecb9
  21:        0x104101f00 - std::rt::lang_start::{{closure}}::hb95f493d3c11ff53
  22:        0x1041b223c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha4b10a239e2af884
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:286:13
  23:        0x1041b223c - std::panicking::try::do_call::h6b4bcb7d3635e86a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  24:        0x1041b223c - std::panicking::try::h579c8cca81ff0f69
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  25:        0x1041b223c - std::panic::catch_unwind::h4a997c12755a6e33
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  26:        0x1041b223c - std::rt::lang_start_internal::{{closure}}::hf20057b44f57f87c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:48
  27:        0x1041b223c - std::panicking::try::do_call::hdfca34da16d8863f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  28:        0x1041b223c - std::panicking::try::h4f4022e500de0807
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  29:        0x1041b223c - std::panic::catch_unwind::h62721286166676e8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  30:        0x1041b223c - std::rt::lang_start_internal::h659a783147314d97
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:20
  31:        0x1040f2a3c - _main
```

Here's the output of `imessage-exporter -d`:
```
Building cache...
[1/4] Caching chats...
[2/4] Caching chatrooms...
[3/4] Caching participants...
[4/4] Caching reactions...
Cache built!

iMessage Database Diagnostics

Messages not associated with a chat: 68
Missing attachment data:
    Missing files: 24
    ck_server_change_token_blob: 7
Duplicated contacts: 63
Duplicated chats: 47
Done!
```

Running `imessage-exporter -f html` works fine and it looks like the message triggering the error is this one (it's the next message at the point of failure):

<img width="281" alt="image" src="https://user-images.githubusercontent.com/1494739/209996781-55d2019d-3999-4571-8dc1-c4216d2ba823.png">

Version for reference:
`imessage-exporter --version`: `iMessage Exporter 0.1.2`

**Comment by ReagentX** [comment]
Thank you for this amazing bug report! The issue appears to be the `unwrap()` call here:

https://github.com/ReagentX/imessage-exporter/blob/71f7cda8796c67223f0e7148dadfd1de4dc50b3a/imessage-exporter/src/exporters/txt.rs#L337

It doesn't crash for HTML exports because the None variant is handled properly there:

https://github.com/ReagentX/imessage-exporter/blob/71f7cda8796c67223f0e7148dadfd1de4dc50b3a/imessage-exporter/src/exporters/html.rs#L544-L550

**Comment by ReagentX** [comment]
There is also another bug there, in the HTML export it doesn't show who send the missing sticker.

**Comment by ReagentX** [comment]
You should be able to avoid this crash by installing the latest update from crates.io with `cargo install imessage-exporter`.

**Comment by Selovert** [comment]
Success; much appreciated :). Glad the bug report was helpful!

<img width="602" alt="image" src="https://user-images.githubusercontent.com/1494739/210006973-b922f0a2-7603-4532-ae47-66b2d7ea99da.png">
